version: '3.8'

services:
  dragonfly:
    restart: unless-stopped
    image: ghcr.io/dragonflydb/dragonfly:latest
    container_name: dragonfly-auth
    ports:
      - '6379:6379'
    networks:
      - authorization
    volumes:
      - dragonfly-auth:/data/dragonfly

  mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb-auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - authorization
    ports:
      - '27017:27017'
    volumes:
      - mongo-auth:/data/db

  authorization-svc:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authorization-svc
    environment:
      - MONGODB_URL=${MONGOURL}
      - API_PREFIX=${API_PREFIX}
      - NODE_ENV=production
    depends_on:
      - mongodb
      - dragonfly
    networks:
      - authorization
    ports:
      - '3001:3001'

volumes:
  mongo-auth:
  dragonfly-auth:

networks:
  authorization:
    driver: bridge
