version: '3.8'

services:
  dragonfly:
    restart: unless-stopped
    image: ghcr.io/dragonflydb/dragonfly:latest
    container_name: dragonfly
    ports:
      - '6379:6379'
    networks:
      - backend
    volumes:
      - dragonfly-data:/data/dragonfly

  mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - backend
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  authotization-svc:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authotization-svc
    environment:
      - MONGODB_URL=${MONGOURL}
    depends_on:
      - mongodb
    networks:
      - backend
    ports:
      - '3001:3001'
    volumes:
      - .:/authorization

volumes:
  authotization-svc:
  mongo-data:
  dragonfly-data:

networks:
  backend:
    driver: bridge
