openapi: 3.0.0
info:
  title: Authorization Microservice
  version: 1.0.0
  description: Authorization microservice for medical consultation application. Handles the authorization of users for the entire application

servers:
  - url: http://localhost:3001

paths:
  # Aquí irán tus rutas

components:
  # Aquí irán tus componentes reutilizables
